version: "2"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  app:
    build: ./app
    ports:
      - "3000:5000"
    depends_on:
      - db
  phpmyadmin:
        image: phpmyadmin
        ports:
            - "8000:80"
        restart: always
        environment:
            - PMA_ARBITRARY=1
        depends_on:
          - db